export const dependencies = {
  "lucide-react": "latest",
  recharts: "2.9.0",
  "@radix-ui/react-accordion": "^1.2.0",
  "@radix-ui/react-alert-dialog": "^1.1.1",
  "@radix-ui/react-aspect-ratio": "^1.1.0",
  "@radix-ui/react-avatar": "^1.1.0",
  "@radix-ui/react-checkbox": "^1.1.1",
  "@radix-ui/react-collapsible": "^1.1.0",
  "@radix-ui/react-dialog": "^1.1.1",
  "@radix-ui/react-dropdown-menu": "^2.1.1",
  "@radix-ui/react-hover-card": "^1.1.1",
  "@radix-ui/react-label": "^2.1.0",
  "@radix-ui/react-menubar": "^1.1.1",
  "@radix-ui/react-navigation-menu": "^1.2.0",
  "@radix-ui/react-popover": "^1.1.1",
  "@radix-ui/react-progress": "^1.1.0",
  "@radix-ui/react-radio-group": "^1.2.0",
  "@radix-ui/react-select": "^2.1.1",
  "@radix-ui/react-separator": "^1.1.0",
  "@radix-ui/react-slider": "^1.2.0",
  "@radix-ui/react-slot": "^1.1.0",
  "@radix-ui/react-switch": "^1.1.0",
  "@radix-ui/react-tabs": "^1.1.0",
  "@radix-ui/react-toast": "^1.2.1",
  "@radix-ui/react-toggle": "^1.1.0",
  "@radix-ui/react-toggle-group": "^1.1.0",
  "@radix-ui/react-tooltip": "^1.1.2",
  "class-variance-authority": "^0.7.0",
  clsx: "^2.1.1",
  "date-fns": "^3.6.0",
  "embla-carousel-react": "^8.1.8",
  "react-day-picker": "^8.10.1",
  "tailwind-merge": "^2.4.0",
  "tailwindcss-animate": "^1.0.7",
  "framer-motion": "^11.15.0",
  vaul: "^0.9.1",
};

export const lucideIcons = `AArrowDown, AArrowUp, ALargeSmall, Accessibility, Activity, AirVent, Airplay, AlarmClockCheck, AlarmClockMinus, AlarmClockOff, AlarmClockPlus, AlarmClock, AlarmSmoke, Album, AlignCenterHorizontal, AlignCenterVertical, AlignCenter, AlignEndHorizontal, AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd, AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd, AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween, AlignJustify, AlignLeft, AlignRight, AlignStartHorizontal, AlignStartVertical, AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart, AlignVerticalJustifyCenter, AlignVerticalJustifyEnd, AlignVerticalJustifyStart, AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ambulance, Ampersand, Ampersands, Amphora, Anchor, Angry, Annoyed, Antenna, Anvil, Aperture, AppWindowMac, AppWindow, Apple, ArchiveRestore, ArchiveX, Archive, Armchair, ArrowBigDownDash, ArrowBigDown, ArrowBigLeftDash, ArrowBigLeft, ArrowBigRightDash, ArrowBigRight, ArrowBigUpDash, ArrowBigUp, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownFromLine, ArrowDownLeft, ArrowDownNarrowWide, ArrowDownRight, ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowDown, ArrowLeftFromLine, ArrowLeftRight, ArrowLeftToLine, ArrowLeft, ArrowRightFromLine, ArrowRightLeft, ArrowRightToLine, ArrowRight, ArrowUp01, ArrowUp10, ArrowUpAZ, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeft, ArrowUpNarrowWide, ArrowUpRight, ArrowUpToLine, ArrowUpWideNarrow, ArrowUpZA, ArrowUp, ArrowsUpFromLine, Asterisk, AtSign, Atom, AudioLines, AudioWaveform, Award, Axe, Axis3d, Baby, Backpack, BadgeAlert, BadgeCent, BadgeCheck, BadgeDollarSign, BadgeEuro, BadgeHelp, BadgeIndianRupee, BadgeInfo, BadgeJapaneseYen, BadgeMinus, BadgePercent, BadgePlus, BadgePoundSterling, BadgeRussianRuble, BadgeSwissFranc, BadgeX, Badge, BaggageClaim, Ban, Banana, Bandage, Banknote, Barcode, Baseline, Bath, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryWarning, Battery, Beaker, BeanOff, Bean, BedDouble, BedSingle, Bed, Beef, BeerOff, Beer, BellDot, BellElectric, BellMinus, BellOff, BellPlus, BellRing, Bell, BetweenHorizontalEnd, BetweenHorizontalStart, BetweenVerticalEnd, BetweenVerticalStart, BicepsFlexed, Bike, Binary, Binoculars, Biohazard, Bird, Bitcoin, Blend, Blinds, Blocks, BluetoothConnected, BluetoothOff, BluetoothSearching, Bluetooth, Bold, Bolt, Bomb, Bone, BookA, BookAudio, BookCheck, BookCopy, BookDashed, BookDown, BookHeadphones, BookHeart, BookImage, BookKey, BookLock, BookMarked, BookMinus, BookOpenCheck, BookOpenText, BookOpen, BookPlus, BookText, BookType, BookUp2, BookUp, BookUser, BookX, Book, BookmarkCheck, BookmarkMinus, BookmarkPlus, BookmarkX, Bookmark, BoomBox, BotMessageSquare, BotOff, Bot, Box, Boxes, Braces, Brackets, BrainCircuit, BrainCog, Brain, BrickWall, BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, Briefcase, BringToFront, Brush, BugOff, BugPlay, Bug, Building2, Building, BusFront, Bus, CableCar, Cable, CakeSlice, Cake, Calculator, Calendar1, CalendarArrowDown, CalendarArrowUp, CalendarCheck2, CalendarCheck, CalendarClock, CalendarCog, CalendarDays, CalendarFold, CalendarHeart, CalendarMinus2, CalendarMinus, CalendarOff, CalendarPlus2, CalendarPlus, CalendarRange, CalendarSearch, CalendarSync, CalendarX2, CalendarX, Calendar, CameraOff, Camera, CandyCane, CandyOff, Candy, Cannabis, CaptionsOff, Captions, CarFront, CarTaxiFront, Car, Caravan, Carrot, CaseLower, CaseSensitive, CaseUpper, CassetteTape, Cast, Castle, Cat, Cctv, ChartArea, ChartBarBig, ChartBarDecreasing, ChartBarIncreasing, ChartBarStacked, ChartBar, ChartCandlestick, ChartColumnBig, ChartColumnDecreasing, ChartColumnIncreasing, ChartColumnStacked, ChartColumn, ChartGantt, ChartLine, ChartNetwork, ChartNoAxesColumnDecreasing, ChartNoAxesColumnIncreasing, ChartNoAxesColumn, ChartNoAxesCombined, ChartNoAxesGantt, ChartPie, ChartScatter, ChartSpline, CheckCheck, Check, ChefHat, Cherry, ChevronDown, ChevronFirst, ChevronLast, ChevronLeft, ChevronRight, ChevronUp, ChevronsDownUp, ChevronsDown, ChevronsLeftRightEllipsis, ChevronsLeftRight, ChevronsLeft, ChevronsRightLeft, ChevronsRight, ChevronsUpDown, ChevronsUp`;
